# Script that generates the alphabet.h file that is used to provide a 
#   representation of characters for the light wand to display

from pathlib import Path
from glob import glob
from PIL import Image
import numpy as np

SOURCE_DIR = Path("./alphabet_source")
CHAR_WIDTH = 21
CHAR_HEIGHT = 30


if __name__ == "__main__":
    print("Generating alphabet...")

    generated_c = """
/*
Generated by scripts/generate_alphabet.py

This h file contains generated representations for characters to be dispalyed on the light wand as arrays of 32-bit integers
Each 32-bit integer in an array is a column of the characer, and each bit in that integer is a pixel. 1's mean on, 0's mean off.

The lowest pixel on the wand is the LSB

*/

"""
    generated_c += "#include <stdint.h>\n\n"
    generated_c += f"#define\tCHAR_WIDTH\t{CHAR_WIDTH}\n#define\tCHAR_HEIGHT\t{CHAR_HEIGHT}\n\n"

    # get all pngs in SOURCE_DIR and generate a C array for that character
    for image in glob("*.png", root_dir=SOURCE_DIR):
        char_name = "CHAR_" + str(image).split('.')[0].upper()
        print(f"    Generating {char_name} from {image}")


        # open the image as an image
        with Image.open(SOURCE_DIR.joinpath(image)) as im:
            # convert the image to a grayscale array of ones and zeroes.
            imarray = np.asarray(im.convert('L')) / 255
            
            # now extract the vertical columns of the image and turn them into 32-bit bitfields
            integers = np.zeros(CHAR_WIDTH, dtype="uint32")
            for col in range(CHAR_WIDTH):
                column = imarray[:, col]

                for i, bit in enumerate(column):
                    integers[col] = integers[col] | ((not int(bit)) << i)

            generated_c += f"const uint32_t {char_name}[CHAR_WIDTH]\t= "
            generated_c += "{"
            for i in integers:
                generated_c += f"0x{i:08x},"

            generated_c = generated_c[:-1]
            generated_c = generated_c + "};\n"

    print("Copy and paste the following code into alphabet.h:")
    print()
    print(generated_c)